"""add datetime column to requests table

Revision ID: 97f2c5becc4d
Revises: 57e08189ec0c
Create Date: 2023-10-07 20:12:05.347676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97f2c5becc4d'
down_revision = '57e08189ec0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('datetime', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.drop_column('datetime')

    # ### end Alembic commands ###
